-- بيانات تجريبية للمعاينة فقط — NAYVO
--
-- الغرض: تعبئة المتجر بمنتجات وبانر سحب حتى تظهر الشاشات بشكلها النهائي
-- قبل إدخال البيانات الحقيقية. هذه ليست بيانات حقيقية ولا يجوز عرضها
-- على أنها كذلك (راجع RELEASE.md).
--
-- التشغيل:
--   docker compose -f docker-compose.prod.yml exec -T db \
--     psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" < scripts/sql/demo-seed.sql
--
-- الحذف (كل ما يضيفه هذا الملف معرّفاته تبدأ بـ demo-):
--   DELETE FROM draws    WHERE id LIKE 'demo-%';
--   DELETE FROM products WHERE id LIKE 'demo-%';
--
-- الصور مضمّنة كـ data: URI بصيغة SVG، فلا تحتاج أي ملفات أو شبكة.

BEGIN;

-- إعادة التشغيل آمنة: نمسح النسخة السابقة من البيانات التجريبية أولاً.
DELETE FROM draws    WHERE id LIKE 'demo-%';
DELETE FROM products WHERE id LIKE 'demo-%';

-- ── المنتجات ─────────────────────────────────────────────────────────
INSERT INTO products (id, name, description, image_url, specs_json, price, stock, category, sort_order, is_active, sold_count) VALUES
  ('demo-p01', 'مكواة بخار احترافية', 'مكواة بخار بقاعدة سيراميك وقدرة 2000 واط، مناسبة للاستخدام اليومي.', 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0MDAgNDAwIj4KPHJlY3Qgd2lkdGg9IjQwMCIgaGVpZ2h0PSI0MDAiIGZpbGw9IiNGN0Y5RkMiLz4KPGNpcmNsZSBjeD0iMjAwIiBjeT0iMTkwIiByPSIxMTgiIGZpbGw9IiNFOEYwRkQiLz4KPGcgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMjAwIDE5MCkiIGZpbGw9Im5vbmUiIHN0cm9rZT0iIzEyNjdFOCIgc3Ryb2tlLXdpZHRoPSIxMSIKICAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIj48cmVjdCB4PSItNjIiIHk9Ii0xNCIgd2lkdGg9IjEyNCIgaGVpZ2h0PSI0NiIgcng9IjE2Ii8+PHBhdGggZD0iTS02MiAtMTQgUS00MCAtNTQgOCAtNTQgTDQ0IC01NCIvPjxwYXRoIGQ9Ik0tNDQgNDYgSDQ0Ii8+PC9nPgo8L3N2Zz4=', '[{"text": "قدرة 2000 واط", "icon": "flash"}, {"text": "قاعدة سيراميك", "icon": "water"}, {"text": "خاصية البخار", "icon": "cloud"}, {"text": "تصميم مريح", "icon": "hand-left"}]', 15, 40, 'home_appliances', 1, true, 0),
  ('demo-p02', 'خلاط صغير متعدد', 'خلاط بسعة 1.5 لتر وشفرات ستانلس، لعصائر وصلصات سريعة.', 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0MDAgNDAwIj4KPHJlY3Qgd2lkdGg9IjQwMCIgaGVpZ2h0PSI0MDAiIGZpbGw9IiNGN0Y5RkMiLz4KPGNpcmNsZSBjeD0iMjAwIiBjeT0iMTkwIiByPSIxMTgiIGZpbGw9IiNFOEYwRkQiLz4KPGcgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMjAwIDE5MCkiIGZpbGw9Im5vbmUiIHN0cm9rZT0iIzEyNjdFOCIgc3Ryb2tlLXdpZHRoPSIxMSIKICAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIj48cGF0aCBkPSJNLTM4IC01OCBIMzggTDI2IDI0IEgtMjYgWiIvPjxyZWN0IHg9Ii0zNCIgeT0iMzAiIHdpZHRoPSI2OCIgaGVpZ2h0PSIzNCIgcng9IjkiLz48cGF0aCBkPSJNLTE0IC0yMCBIMTQiLz48L2c+Cjwvc3ZnPg==', '[{"text": "قدرة 700 واط", "icon": "flash"}, {"text": "سعة 1.5 لتر", "icon": "cube"}, {"text": "شفرات ستانلس", "icon": "cut"}, {"text": "أجزاء قابلة للغسل", "icon": "water"}]', 15, 35, 'kitchen', 2, true, 0),
  ('demo-p03', 'غلاية ماء كهربائية', 'غلاية ستانلس ستيل 1.7 لتر بإطفاء تلقائي عند الغليان.', 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0MDAgNDAwIj4KPHJlY3Qgd2lkdGg9IjQwMCIgaGVpZ2h0PSI0MDAiIGZpbGw9IiNGN0Y5RkMiLz4KPGNpcmNsZSBjeD0iMjAwIiBjeT0iMTkwIiByPSIxMTgiIGZpbGw9IiNFOEYwRkQiLz4KPGcgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMjAwIDE5MCkiIGZpbGw9Im5vbmUiIHN0cm9rZT0iIzEyNjdFOCIgc3Ryb2tlLXdpZHRoPSIxMSIKICAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIj48cmVjdCB4PSItNDQiIHk9Ii0yNiIgd2lkdGg9Ijg4IiBoZWlnaHQ9IjgwIiByeD0iMTgiLz48cGF0aCBkPSJNNDQgLTYgcTI2IDEwIDAgMzAiLz48cGF0aCBkPSJNLTI2IC0yNiBxMjYgLTM0IDUyIDAiLz48L2c+Cjwvc3ZnPg==', '[{"text": "قدرة 1800 واط", "icon": "flash"}, {"text": "سعة 1.7 لتر", "icon": "cube"}, {"text": "إطفاء تلقائي", "icon": "shield-checkmark"}, {"text": "حفظ الحرارة", "icon": "thermometer"}]', 15, 50, 'kitchen', 3, true, 0),
  ('demo-p04', 'مفرمة كهربائية', 'مفرمة بوعاء زجاجي وشفرتين، تفرم اللحوم والخضار بثوانٍ.', 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0MDAgNDAwIj4KPHJlY3Qgd2lkdGg9IjQwMCIgaGVpZ2h0PSI0MDAiIGZpbGw9IiNGN0Y5RkMiLz4KPGNpcmNsZSBjeD0iMjAwIiBjeT0iMTkwIiByPSIxMTgiIGZpbGw9IiNFOEYwRkQiLz4KPGcgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMjAwIDE5MCkiIGZpbGw9Im5vbmUiIHN0cm9rZT0iIzEyNjdFOCIgc3Ryb2tlLXdpZHRoPSIxMSIKICAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIj48cmVjdCB4PSItNDIiIHk9Ii0xNiIgd2lkdGg9Ijg0IiBoZWlnaHQ9IjY2IiByeD0iMTQiLz48cGF0aCBkPSJNLTMwIC0xNiBWLTQyIGg2MCB2MjYiLz48cGF0aCBkPSJNLTEyIDggTDEyIDMyIE0xMiA4IEwtMTIgMzIiLz48L2c+Cjwvc3ZnPg==', '[{"text": "قدرة 500 واط", "icon": "flash"}, {"text": "وعاء زجاجي", "icon": "cube"}, {"text": "شفرتان", "icon": "cut"}, {"text": "تشغيل بلمسة", "icon": "flash-off"}]', 15, 30, 'kitchen', 4, true, 0),
  ('demo-p05', 'سماعات لاسلكية', 'سماعات بلوتوث 5.3 مع عزل ضجيج وبطارية تدوم 30 ساعة.', 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0MDAgNDAwIj4KPHJlY3Qgd2lkdGg9IjQwMCIgaGVpZ2h0PSI0MDAiIGZpbGw9IiNGN0Y5RkMiLz4KPGNpcmNsZSBjeD0iMjAwIiBjeT0iMTkwIiByPSIxMTgiIGZpbGw9IiNFOEYwRkQiLz4KPGcgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMjAwIDE5MCkiIGZpbGw9Im5vbmUiIHN0cm9rZT0iIzBCMjE0MiIgc3Ryb2tlLXdpZHRoPSIxMSIKICAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIj48cGF0aCBkPSJNLTUyIDE2IHYtMTQgYTUyIDUyIDAgMCAxIDEwNCAwIHYxNCIvPjxyZWN0IHg9Ii02NCIgeT0iMTIiIHdpZHRoPSIyNiIgaGVpZ2h0PSI0NCIgcng9IjEyIi8+PHJlY3QgeD0iMzgiIHk9IjEyIiB3aWR0aD0iMjYiIGhlaWdodD0iNDQiIHJ4PSIxMiIvPjwvZz4KPC9zdmc+', '[{"text": "بلوتوث 5.3", "icon": "bluetooth"}, {"text": "30 ساعة تشغيل", "icon": "battery-full"}, {"text": "عزل ضجيج", "icon": "volume-off"}, {"text": "مايك مدمج", "icon": "mic"}]', 30, 25, 'electronics', 5, true, 0),
  ('demo-p06', 'ساعة ذكية رياضية', 'ساعة بشاشة AMOLED وتتبّع نبض ونوم ومقاومة ماء.', 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0MDAgNDAwIj4KPHJlY3Qgd2lkdGg9IjQwMCIgaGVpZ2h0PSI0MDAiIGZpbGw9IiNGN0Y5RkMiLz4KPGNpcmNsZSBjeD0iMjAwIiBjeT0iMTkwIiByPSIxMTgiIGZpbGw9IiNFOEYwRkQiLz4KPGcgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMjAwIDE5MCkiIGZpbGw9Im5vbmUiIHN0cm9rZT0iIzBCMjE0MiIgc3Ryb2tlLXdpZHRoPSIxMSIKICAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIj48cmVjdCB4PSItMzQiIHk9Ii0zNCIgd2lkdGg9IjY4IiBoZWlnaHQ9IjY4IiByeD0iMTgiLz48cGF0aCBkPSJNLTE4IC0zNCBWLTU4IGgzNiB2MjQgTS0xOCAzNCBWNTggaDM2IFYzNCIvPjxwYXRoIGQ9Ik0wIC0xMiBWMCBoMTQiLz48L2c+Cjwvc3ZnPg==', '[{"text": "شاشة AMOLED", "icon": "phone-portrait"}, {"text": "تتبّع النبض", "icon": "heart"}, {"text": "مقاومة ماء", "icon": "water"}, {"text": "7 أيام بطارية", "icon": "battery-full"}]', 45, 20, 'electronics', 6, true, 0),
  ('demo-p07', 'شاحن سريع 65 واط', 'شاحن بثلاثة منافذ يشحن الهاتف واللابتوب بنفس الوقت.', 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0MDAgNDAwIj4KPHJlY3Qgd2lkdGg9IjQwMCIgaGVpZ2h0PSI0MDAiIGZpbGw9IiNGN0Y5RkMiLz4KPGNpcmNsZSBjeD0iMjAwIiBjeT0iMTkwIiByPSIxMTgiIGZpbGw9IiNFOEYwRkQiLz4KPGcgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMjAwIDE5MCkiIGZpbGw9Im5vbmUiIHN0cm9rZT0iIzBCMjE0MiIgc3Ryb2tlLXdpZHRoPSIxMSIKICAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIj48cmVjdCB4PSItMzYiIHk9Ii0zMCIgd2lkdGg9IjcyIiBoZWlnaHQ9IjYyIiByeD0iMTQiLz48cGF0aCBkPSJNLTE2IC0zMCBWLTU4IE0xNiAtMzAgVi01OCIvPjxwYXRoIGQ9Ik0wIDMyIHYxNiBxMCAxMiAxOCAxMiBoMTQiLz48L2c+Cjwvc3ZnPg==', '[{"text": "65 واط", "icon": "flash"}, {"text": "ثلاثة منافذ", "icon": "grid"}, {"text": "حماية من الحرارة", "icon": "shield-checkmark"}, {"text": "حجم مدمج", "icon": "cube"}]', 20, 60, 'electronics', 7, true, 0),
  ('demo-p08', 'مصباح مكتب LED', 'مصباح بثلاث درجات إضاءة وذراع قابلة للتعديل.', 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0MDAgNDAwIj4KPHJlY3Qgd2lkdGg9IjQwMCIgaGVpZ2h0PSI0MDAiIGZpbGw9IiNGN0Y5RkMiLz4KPGNpcmNsZSBjeD0iMjAwIiBjeT0iMTkwIiByPSIxMTgiIGZpbGw9IiNFOEYwRkQiLz4KPGcgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMjAwIDE5MCkiIGZpbGw9Im5vbmUiIHN0cm9rZT0iI0Y1QjczMSIgc3Ryb2tlLXdpZHRoPSIxMSIKICAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIj48cGF0aCBkPSJNLTQyIC0xNiBMLTI0IC01OCBIMjQgTDQyIC0xNiBaIi8+PHBhdGggZD0iTS0xNiAtMTYgSDE2Ii8+PHBhdGggZD0iTTAgLTE2IFY0MCIvPjxwYXRoIGQ9Ik0tMjggNTIgSDI4Ii8+PC9nPgo8L3N2Zz4=', '[{"text": "ثلاث درجات إضاءة", "icon": "sunny"}, {"text": "ذراع متحركة", "icon": "resize"}, {"text": "توفير طاقة", "icon": "flash"}, {"text": "مريح للعين", "icon": "eye"}]', 15, 45, 'home_appliances', 8, true, 0),
  ('demo-p09', 'مروحة مكتبية هادئة', 'مروحة بثلاث سرعات ومحرك هادئ مناسب للمكتب.', 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0MDAgNDAwIj4KPHJlY3Qgd2lkdGg9IjQwMCIgaGVpZ2h0PSI0MDAiIGZpbGw9IiNGN0Y5RkMiLz4KPGNpcmNsZSBjeD0iMjAwIiBjeT0iMTkwIiByPSIxMTgiIGZpbGw9IiNFOEYwRkQiLz4KPGcgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMjAwIDE5MCkiIGZpbGw9Im5vbmUiIHN0cm9rZT0iI0Y1QjczMSIgc3Ryb2tlLXdpZHRoPSIxMSIKICAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIj48Y2lyY2xlIGN4PSIwIiBjeT0iMCIgcj0iMTQiLz48cGF0aCBkPSJNMCAtMTQgcS0zOCAtMzQgLTYgLTQ0IHEzMCAtOCA2IDQ0Ii8+PHBhdGggZD0iTTEyIDYgcTQ4IC0xMCA0MiAyMiBxLTggMzAgLTQyIC0yMiIvPjxwYXRoIGQ9Ik0tMTIgNiBxLTEwIDQ4IC00MiAyMiBxLTIyIC0yMiA0MiAtMjIiLz48L2c+Cjwvc3ZnPg==', '[{"text": "ثلاث سرعات", "icon": "flash"}, {"text": "محرك هادئ", "icon": "volume-off"}, {"text": "زاوية قابلة للتعديل", "icon": "resize"}, {"text": "قاعدة ثابتة", "icon": "cube"}]', 15, 38, 'home_appliances', 9, true, 0),
  ('demo-p10', 'طقم أكواب سيراميك', 'أربعة أكواب سيراميك بتصميم بسيط، آمنة بالميكروويف.', 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0MDAgNDAwIj4KPHJlY3Qgd2lkdGg9IjQwMCIgaGVpZ2h0PSI0MDAiIGZpbGw9IiNGN0Y5RkMiLz4KPGNpcmNsZSBjeD0iMjAwIiBjeT0iMTkwIiByPSIxMTgiIGZpbGw9IiNFOEYwRkQiLz4KPGcgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMjAwIDE5MCkiIGZpbGw9Im5vbmUiIHN0cm9rZT0iI0Y1QjczMSIgc3Ryb2tlLXdpZHRoPSIxMSIKICAgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIj48cGF0aCBkPSJNLTM4IC0zNCBIMjYgVjI2IGEyMCAyMCAwIDAgMSAtMjAgMjAgSC0xOCBhMjAgMjAgMCAwIDEgLTIwIC0yMCBaIi8+PHBhdGggZD0iTTI2IC0xNCBxMjggNiAwIDI2Ii8+PHBhdGggZD0iTS00NCA2MCBINDAiLz48L2c+Cjwvc3ZnPg==', '[{"text": "أربع قطع", "icon": "cube"}, {"text": "آمنة بالميكروويف", "icon": "flame"}, {"text": "آمنة بغسالة الصحون", "icon": "water"}, {"text": "تصميم بسيط", "icon": "color-palette"}]', 15, 55, 'kitchen', 10, true, 0)
;

-- ── جولات السحب (البانر في الرئيسية وصفحة السحب) ─────────────────────
-- الجولة النشطة: sold_tickets مضبوط ليظهر شريط التقدّم بشكله الطبيعي.
-- ملاحظة: هذا رقم عرض فقط ولا تقابله تذاكر حقيقية في جدول tickets،
-- فلا تُجرِ سحباً فعلياً على هذه الجولة التجريبية.
INSERT INTO draws (id, title, prize_name, prize_description, prize_image_url,
                   ticket_price, target_tickets, sold_tickets, status, sort_order, started_at) VALUES
  ('demo-d01', 'الجولة الأولى', 'آيفون 15 برو',
   'آيفون 15 برو ٢٥٦ غيغا — جائزة الجولة الأولى، يُسلَّم للفائز بعد إعلان النتيجة.',
   'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMjAgNDAwIj4KPHJlY3Qgd2lkdGg9IjMyMCIgaGVpZ2h0PSI0MDAiIGZpbGw9IiNGRkZGRkYiLz4KPHJlY3QgeD0iNDQiIHk9IjcyIiB3aWR0aD0iMjMyIiBoZWlnaHQ9IjI1NiIgcng9IjI4IiBmaWxsPSIjMEIyMTQyIi8+CjxjaXJjbGUgY3g9IjE2MCIgY3k9IjIwMCIgcj0iOTYiIGZpbGw9IiMxMjY3RTgiIG9wYWNpdHk9IjAuMzAiLz4KPGcgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMTYwIDIwMCkiIGZpbGw9Im5vbmUiIHN0cm9rZT0iI0Y1QjczMSIgc3Ryb2tlLXdpZHRoPSI5IgogICBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiPjxyZWN0IHg9Ii0zMCIgeT0iLTU2IiB3aWR0aD0iNjAiIGhlaWdodD0iMTEyIiByeD0iMTIiLz48cGF0aCBkPSJNLTkgLTQyIEg5Ii8+PGNpcmNsZSBjeD0iMCIgY3k9IjQwIiByPSI0Ii8+PC9nPgo8L3N2Zz4=',
   10, 1000, 640, 'active', 1, now()),
  ('demo-d02', 'الجولة الثانية', 'لابتوب ماك بوك إير',
   'ماك بوك إير بمعالج M3 — جائزة الجولة القادمة، تبدأ فور اكتمال الجولة الحالية.',
   'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMjAgNDAwIj4KPHJlY3Qgd2lkdGg9IjMyMCIgaGVpZ2h0PSI0MDAiIGZpbGw9IiNGRkZGRkYiLz4KPHJlY3QgeD0iNDQiIHk9IjcyIiB3aWR0aD0iMjMyIiBoZWlnaHQ9IjI1NiIgcng9IjI4IiBmaWxsPSIjMEIyMTQyIi8+CjxjaXJjbGUgY3g9IjE2MCIgY3k9IjIwMCIgcj0iOTYiIGZpbGw9IiMxMjY3RTgiIG9wYWNpdHk9IjAuMzAiLz4KPGcgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMTYwIDIwMCkiIGZpbGw9Im5vbmUiIHN0cm9rZT0iI0Y1QjczMSIgc3Ryb2tlLXdpZHRoPSI5IgogICBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiPjxwYXRoIGQ9Ik0tNTYgLTM0IGgxMTIgdjY4IGgtMTEyIHoiLz48cGF0aCBkPSJNLTc2IDM0IGgxNTIgbC0xMiAyMiBoLTEyOCB6Ii8+PHBhdGggZD0iTS0zMCAtOCBoNjAiLz48L2c+Cjwvc3ZnPg==',
   10, 1500, 0, 'scheduled', 2, NULL);

COMMIT;
